version: "3"
services:
  mysql:
    image: mysql:8.0.26
    container_name: database_for_mysql
    ports:
      - "33333:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=Asd123456Asd
  mailserver:
    build: .
    container_name: mailserver_for_postfix
    ports:
      - "22587:587"
      - "22465:465"
      - "22993:993"
      - "22995:995"
    volumes:
      - ./mail/logs/postfix:/var/log/postfix
      - ./mail/logs/dovecot:/var/log/dovecot
      - ./mail/data:/var/spool/postfix
    depends_on:
      - mysql
